spring:
  application:
    name: zuul

  rabbitmq:
    host: 192.168.253.132 
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

##默认规则      
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**       


zuul: 
  retryable: true     #启用重试
  
#hystris的超时时间  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500  
            
            
ribbon:
  ConnectTimeout: 1000    #1秒
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1   #重试
  MaxAutoRetries: 1
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
              